# Generated by Django 6.0.2 on 2026-02-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='city',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='department',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='district',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='state',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_at',
            field=models.DateTimeField(auto_created=True, db_column='created_at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, db_column='modified_at', null=True, verbose_name='Modified at'),
        ),
    ]
