# Generated by Django 6.0.2 on 2026-02-20 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(db_column='id_branch', on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.RESTRICT, related_name='sales', to='core.employee'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.RESTRICT, related_name='sale_items', to='core.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(db_column='id_sale', on_delete=django.db.models.deletion.RESTRICT, related_name='sale_items', to='core.sale'),
        ),
    ]
