# Generated by Django 6.0.2 on 2026-02-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_city_custumer_department_district_employee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='productgroup',
            old_name='comission_percentage',
            new_name='commission_percentage',
        ),
    ]
