# Generated by Django 6.0.2 on 2026-02-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_branch_active_alter_city_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='city',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='department',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='district',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='state',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='active',
            field=models.BooleanField(db_column='active'),
        ),
    ]
