# Generated by Django 6.0.2 on 2026-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'managed': True, 'ordering': ('-active', '-id'), 'verbose_name': 'Product Group', 'verbose_name_plural': 'Product Groups'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'managed': True, 'ordering': ('-active', '-id'), 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AddIndex(
            model_name='productgroup',
            index=models.Index(fields=['name'], name='product_gro_name_3cd3be_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['name'], name='State_name_d6b465_idx'),
        ),
        migrations.AlterModelTable(
            name='productgroup',
            table='product_group',
        ),
        migrations.AlterModelTable(
            name='state',
            table='State',
        ),
    ]
