# Generated by Django 6.0.2 on 2026-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_productgroup_options_alter_state_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'managed': True, 'ordering': ('name', '-state'), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'managed': True, 'ordering': ('-name', 'abbreviation'), 'verbose_name': 'State', 'verbose_name_plural': 'States'},
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='City_name_6e16b6_idx'),
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
    ]
